name: 디스코드 알림봇

on:
  schedule:
    - cron: "18 14 * * *"   # 매일 11:18 UTC = 23:18 KST
  workflow_dispatch:

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "일일퀘스트, 접속보상, 추천, 수박 하슈. 뿡"

